name: Deploy to Azure

on:
  push:
    branches: [ main ]
    paths:
      - 'Backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        
    - name: Install Dependencies
      run: |
        cd Backend
        npm install
        
    - name: Prepare for deployment
      run: |
        cd Backend
        mkdir -p deploy
        cp -r src package.json package-lock.json .env* deploy/
        
    - name: Create startup command file
      run: |
        cd Backend/deploy
        echo "cd /home/site/wwwroot && npm install && PORT=8080 node src/app.js" > startup.sh
        chmod +x startup.sh
        
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: Backend/deploy