name: Deploy to Azure

on:
  push:
    branches: [ main ]
    paths:
      - 'Backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
        
    - name: Prepare deployment
      run: |
        mkdir -p Backend/deploy
        cp Backend/package*.json Backend/deploy/
        cp -r Backend/src Backend/deploy/
        
        # Create startup script with debug logging
        cat > Backend/deploy/startup.sh << 'EOL'
#!/bin/sh
echo "Starting deployment script..."
pwd
ls -la

cd /home/site/wwwroot
echo "Changed to wwwroot directory"
pwd
ls -la

echo "Installing dependencies..."
npm install --production

echo "Starting application..."
node src/app.js
EOL
        
        # Set permissions
        chmod 755 Backend/deploy/startup.sh
        
        # Verify deployment
        echo "Deployment contents:"
        ls -la Backend/deploy
        echo "Startup script contents:"
        cat Backend/deploy/startup.sh
        
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: Backend/deploy