name: Deploy to Azure

on:
  push:
    branches: [ main ]
    paths:
      - 'Backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
        
    - name: Prepare deployment
      run: |
        mkdir -p Backend/deploy
        cp Backend/package*.json Backend/deploy/
        cp -r Backend/src Backend/deploy/
        
        # Create startup script with Unix line endings
        cat > Backend/deploy/startup.sh << 'EOL'
#!/bin/sh
cd /home/site/wwwroot
npm install --production
node src/app.js
EOL
        
        # Ensure correct permissions and line endings
        chmod +x Backend/deploy/startup.sh
        dos2unix Backend/deploy/startup.sh || true
        
        # Verify deployment structure
        ls -la Backend/deploy
        cat Backend/deploy/startup.sh
        
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: Backend/deploy