name: Deploy to Azure

on:
  push:
    branches: [ main ]
    paths:
      - 'Backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
        
    - name: Prepare deployment
      run: |
        # Create deployment directory
        mkdir -p Backend/deploy
        
        # Copy application files
        cp Backend/package*.json Backend/deploy/
        cp -r Backend/src Backend/deploy/src
        
        # Create startup command file
        echo "#!/bin/sh
        echo 'Current directory before:'
        pwd
        ls -la
        
        echo 'Installing dependencies...'
        npm install --production
        
        echo 'Starting application...'
        node src/app.js" > Backend/deploy/startup.sh
        
        # Set correct permissions
        chmod +x Backend/deploy/startup.sh
        
        # Debug output
        echo "Final deployment structure:"
        ls -la Backend/deploy
        echo "Startup script contents:"
        cat Backend/deploy/startup.sh
        
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: Backend/deploy