name: Deploy to Azure

on:
  push:
    branches: [ main ]
    paths:
      - 'Backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        
    - name: Prepare deployment
      run: |
        mkdir -p Backend/deploy
        cp Backend/package*.json Backend/deploy/
        cp -r Backend/src Backend/deploy/
        cp Backend/.env* Backend/deploy/ || true
        
        # Handle startup script properly
        cp Backend/startup.sh Backend/deploy/
        sed -i 's/\r$//' Backend/deploy/startup.sh
        chmod +x Backend/deploy/startup.sh
        
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: Backend/deploy