name: Nightly Scraper

on:
  schedule:
    - cron: '0 4 * * *'  # Runs at midnight EST (4:00 UTC)
  workflow_dispatch:  # Allows manual triggers

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m nltk.downloader wordnet
        python -m nltk.downloader omw-1.4
        
    - name: Run scraper
      env:
        # MongoDB Configuration
        MONGO_USER: ${{ secrets.MONGO_USER }}
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        MONGO_HOST: ${{ secrets.MONGO_HOST }}
        MONGO_DB: ${{ secrets.MONGO_DB }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        
        # Flipp API Configuration
        FLIPP_BASE_URL: ${{ secrets.FLIPP_BASE_URL }}
        FLIPP_MERCHANTS_ENDPOINT: '/merchants'
        FLIPP_ITEMS_SEARCH_ENDPOINT: '/items/search'
        FLIPP_FLYERS_ENDPOINT: '/flyers'
        FLIPP_ITEMS_ENDPOINT: '/items'
        FLIPP_DATA_ENDPOINT: '/data'
        FLIPP_CAT_DICT_ENDPOINT: '/cat_dict'
        FLIPP_LOCALE: 'en-ca'
        
        # Postal Codes
        DEFAULT_POSTAL_CODE: 'K1P1J1'
        POSTAL_CODES: 'K1P1J1,M5R2E3,N2L3G1,K7L3N6'
        
      run: python "Data Collection/scraper.py"